/**
 * Bangumi API
 * 你可以在 <https://next.bgm.tv/demo/access-token> 生成一个 Access Token  ## [关于 User Agent](https://github.com/bangumi/api/blob/master/docs-raw/user%20agent.md)  如果你在使用中遇到了问题，请优先使用 GitHub issue 提交问题。在 bangumi 小组发帖可能无法得到及时反馈。 
 *
 * The version of the OpenAPI document: 2025-02-5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * - `0`: 未收藏 - `1`: 想看 - `2`: 看过 - `3`: 抛弃
 */
export type EpisodeCollectionType = 1 | 2 | 3;

export const EpisodeCollectionType = {
    NUMBER_1: 1 as EpisodeCollectionType,
    NUMBER_2: 2 as EpisodeCollectionType,
    NUMBER_3: 3 as EpisodeCollectionType
}
