/**
 * Bangumi API
 * 你可以在 <https://next.bgm.tv/demo/access-token> 生成一个 Access Token  ## [关于 User Agent](https://github.com/bangumi/api/blob/master/docs-raw/user%20agent.md)  如果你在使用中遇到了问题，请优先使用 GitHub issue 提交问题。在 bangumi 小组发帖可能无法得到及时反馈。 
 *
 * The version of the OpenAPI document: 2025-02-5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Episode { 
    id: number;
    /**
     * `0` 本篇，`1` SP，`2` OP，`3` ED
     */
    type: number;
    name: string;
    name_cn: string;
    /**
     * 同类条目的排序和集数
     */
    sort: number;
    /**
     * 条目内的集数, 从`1`开始。非本篇剧集的此字段无意义
     */
    ep?: number;
    airdate: string;
    comment: number;
    /**
     * 维基人填写的原始时长
     */
    duration: string;
    /**
     * 简介
     */
    desc: string;
    /**
     * 音乐曲目的碟片数
     */
    disc: number;
    /**
     * 服务器解析的时长，无法解析时为 `0`
     */
    duration_seconds?: number;
}
