/**
 * Bangumi API
 * 你可以在 <https://api.bgm.tv/v0/oauth/> 生成一个 Access Token  ## 建议客户端开发者指定一个带有 APP 名称和版本的 User Agent，而非使用 HTTP 请求库默认的 UA  各种请求库的默认 UA 在未来可能会被禁用。 
 *
 * The version of the OpenAPI document: 2022-05-3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Episode { 
    id: number;
    /**
     * `0` 本篇，`1` SP，`2` OP，`3` ED
     */
    type: number;
    name: string;
    name_cn: string;
    /**
     * 同类条目的排序和集数
     */
    sort: number;
    /**
     * 条目内的集数, 从`1`开始。非本篇剧集的此字段无意义
     */
    ep?: number;
    airdate: string;
    comment: number;
    duration: string;
    /**
     * 简介
     */
    desc: string;
    /**
     * 音乐曲目的碟片数
     */
    disc: number;
}
