/**
 * Bangumi API
 * 你可以在 <https://next.bgm.tv/demo/access-token> 生成一个 Access Token  ## [关于 User Agent](https://github.com/bangumi/api/blob/master/docs-raw/user%20agent.md)  如果你在使用中遇到了问题，请优先使用 GitHub issue 提交问题。在 bangumi 小组发帖可能无法得到及时反馈。 
 *
 * The version of the OpenAPI document: 2025-02-5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 本篇 = 0 特别篇 = 1 OP = 2 ED = 3 预告/宣传/广告 = 4 MAD = 5 其他 = 6
 */
export type EpType = 0 | 1 | 2 | 3 | 4 | 5 | 6;

export const EpType = {
    MainStory: 0 as EpType,
    SP: 1 as EpType,
    OP: 2 as EpType,
    ED: 3 as EpType,
    PV: 4 as EpType,
    MAD: 5 as EpType,
    Other: 6 as EpType
}
