/**
 * Bangumi API
 * 你可以在 <https://api.bgm.tv/v0/oauth/> 生成一个 Access Token  ## 建议客户端开发者指定一个带有 APP 名称和版本的 User Agent，而非使用 HTTP 请求库默认的 UA  各种请求库的默认 UA 在未来可能会被禁用。 
 *
 * The version of the OpenAPI document: 2022-04-23
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 本篇 = 0 特别篇 = 1 OP = 2 ED = 3 预告/宣传/广告 = 4 MAD = 5 其他 = 6
 */
export type EpType = 0 | 1 | 2 | 3 | 4 | 5 | 6;

export const EpType = {
    MainStory: 0 as EpType,
    SP: 1 as EpType,
    OP: 2 as EpType,
    ED: 3 as EpType,
    PV: 4 as EpType,
    MAD: 5 as EpType,
    Other: 6 as EpType
}
