/**
 * Bangumi API
 * 你可以在 <https://next.bgm.tv/demo/access-token> 生成一个 Access Token  ## [关于 User Agent](https://github.com/bangumi/api/blob/master/docs-raw/user%20agent.md)  如果你在使用中遇到了问题，请优先使用 GitHub issue 提交问题。在 bangumi 小组发帖可能无法得到及时反馈。 
 *
 * The version of the OpenAPI document: 2025-02-5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Avatar } from './avatar';
import { UserGroup } from './userGroup';


export interface GetMyself200Response { 
    id: number;
    /**
     * 唯一用户名，初始与 UID 相同，可修改一次
     */
    username: string;
    nickname: string;
    user_group: UserGroup;
    avatar: Avatar;
    /**
     * 个人签名
     */
    sign: string;
    /**
     * 用户绑定的邮箱地址
     */
    email: string;
    /**
     * 用户注册时间。比如 2017-12-03T08:51:16+08:00
     */
    reg_time: string;
    /**
     * 用户设置的时区偏移，以小时为单位。比如 GMT+8（shanghai/beijing）为 8
     */
    time_offset?: number;
}
export namespace GetMyself200Response {
}
