/**
 * Bangumi API
 * 你可以在 <https://next.bgm.tv/demo/access-token> 生成一个 Access Token  ## [关于 User Agent](https://github.com/bangumi/api/blob/master/docs-raw/user%20agent.md)  如果你在使用中遇到了问题，请优先使用 GitHub issue 提交问题。在 bangumi 小组发帖可能无法得到及时反馈。 
 *
 * The version of the OpenAPI document: 2025-02-5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LegacyUserAvatar } from './legacyUserAvatar';
import { LegacyUserGroup } from './legacyUserGroup';


/**
 * 用户信息
 */
export interface LegacyUser { 
    /**
     * 用户 id
     */
    id?: number;
    /**
     * 用户主页地址
     */
    url?: string;
    /**
     * 用户名
     */
    username?: string;
    /**
     * 昵称
     */
    nickname?: string;
    avatar?: LegacyUserAvatar;
    /**
     * 签名
     */
    sign?: string;
    usergroup?: LegacyUserGroup;
}
export namespace LegacyUser {
}
