/**
 * Bangumi API
 * 你可以在 <https://next.bgm.tv/demo/access-token> 生成一个 Access Token  ## [关于 User Agent](https://github.com/bangumi/api/blob/master/docs-raw/user%20agent.md)  如果你在使用中遇到了问题，请优先使用 GitHub issue 提交问题。在 bangumi 小组发帖可能无法得到及时反馈。 
 *
 * The version of the OpenAPI document: 2025-02-5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 用户组 <br> 1 = 管理员 <br> 2 = Bangumi 管理猿 <br> 3 = 天窗管理猿 <br> 4 = 禁言用户 <br> 5 = 禁止访问用户 <br> 8 = 人物管理猿 <br> 9 = 维基条目管理猿 <br> 10 = 用户 <br> 11 = 维基人
 */
export type LegacyUserGroup = 1 | 2 | 3 | 4 | 5 | 8 | 9 | 10 | 11;

export const LegacyUserGroup = {
    NUMBER_1: 1 as LegacyUserGroup,
    NUMBER_2: 2 as LegacyUserGroup,
    NUMBER_3: 3 as LegacyUserGroup,
    NUMBER_4: 4 as LegacyUserGroup,
    NUMBER_5: 5 as LegacyUserGroup,
    NUMBER_8: 8 as LegacyUserGroup,
    NUMBER_9: 9 as LegacyUserGroup,
    NUMBER_10: 10 as LegacyUserGroup,
    NUMBER_11: 11 as LegacyUserGroup
}
