/**
 * Bangumi API
 * 你可以在 <https://next.bgm.tv/demo/access-token> 生成一个 Access Token  ## [关于 User Agent](https://github.com/bangumi/api/blob/master/docs-raw/user%20agent.md)  如果你在使用中遇到了问题，请优先使用 GitHub issue 提交问题。在 bangumi 小组发帖可能无法得到及时反馈。 
 *
 * The version of the OpenAPI document: 2025-02-5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 章节类型 <br> 0 = 本篇 <br> 1 = 特别篇 <br> 2 = OP <br> 3 = ED <br> 4 = 预告/宣传/广告 <br> 5 = MAD <br> 6 = 其他
 */
export type LegacyEpisodeType = 0 | 1 | 2 | 3 | 4 | 5 | 6;

export const LegacyEpisodeType = {
    NUMBER_0: 0 as LegacyEpisodeType,
    NUMBER_1: 1 as LegacyEpisodeType,
    NUMBER_2: 2 as LegacyEpisodeType,
    NUMBER_3: 3 as LegacyEpisodeType,
    NUMBER_4: 4 as LegacyEpisodeType,
    NUMBER_5: 5 as LegacyEpisodeType,
    NUMBER_6: 6 as LegacyEpisodeType
}
