/**
 * Bangumi API
 * 你可以在 <https://next.bgm.tv/demo/access-token> 生成一个 Access Token  ## [关于 User Agent](https://github.com/bangumi/api/blob/master/docs-raw/user%20agent.md)  如果你在使用中遇到了问题，请优先使用 GitHub issue 提交问题。在 bangumi 小组发帖可能无法得到及时反馈。 
 *
 * The version of the OpenAPI document: 2025-02-5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 条目类型 <br> 1 = book <br> 2 = anime <br> 3 = music <br> 4 = game <br> 6 = real
 */
export type LegacySubjectType = 1 | 2 | 3 | 4 | 6;

export const LegacySubjectType = {
    NUMBER_1: 1 as LegacySubjectType,
    NUMBER_2: 2 as LegacySubjectType,
    NUMBER_3: 3 as LegacySubjectType,
    NUMBER_4: 4 as LegacySubjectType,
    NUMBER_6: 6 as LegacySubjectType
}
