/**
 * Bangumi API
 * 你可以在 <https://next.bgm.tv/demo/access-token> 生成一个 Access Token  ## [关于 User Agent](https://github.com/bangumi/api/blob/master/docs-raw/user%20agent.md)  如果你在使用中遇到了问题，请优先使用 GitHub issue 提交问题。在 bangumi 小组发帖可能无法得到及时反馈。 
 *
 * The version of the OpenAPI document: 2025-02-5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LegacyMonoBaseImages } from './legacyMonoBaseImages';
import { LegacyMonoInfo } from './legacyMonoInfo';


/**
 * 现实人物
 */
export interface LegacyPerson { 
    /**
     * 人物 ID
     */
    id?: number;
    /**
     * 人物地址
     */
    url?: string;
    /**
     * 姓名
     */
    name?: string;
    images?: LegacyMonoBaseImages;
    /**
     * 简体中文名
     */
    name_cn?: string;
    /**
     * 回复数量
     */
    comment?: number;
    /**
     * 收藏人数
     */
    collects?: number;
    info?: LegacyMonoInfo;
}
