/**
 * Bangumi API
 * 你可以在 <https://next.bgm.tv/demo/access-token> 生成一个 Access Token  ## [关于 User Agent](https://github.com/bangumi/api/blob/master/docs-raw/user%20agent.md)  如果你在使用中遇到了问题，请优先使用 GitHub issue 提交问题。在 bangumi 小组发帖可能无法得到及时反馈。 
 *
 * The version of the OpenAPI document: 2025-02-5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Images } from './images';
import { SubjectType } from './subjectType';
import { Tag } from './tag';


export interface SlimSubject { 
    id: number;
    type: SubjectType;
    name: string;
    name_cn: string;
    /**
     * 截短后的条目描述。
     */
    short_summary: string;
    /**
     * air date in `YYYY-MM-DD` format
     */
    date?: string;
    images: Images;
    /**
     * 书籍条目的册数，由旧服务端从wiki中解析
     */
    volumes: number;
    /**
     * 由旧服务端从wiki中解析，对于书籍条目为`话数`
     */
    eps: number;
    /**
     * 收藏人数
     */
    collection_total: number;
    /**
     * 分数
     */
    score: number;
    /**
     * 排名
     */
    rank: number;
    /**
     * 前 10 个 tag
     */
    tags: Array<Tag>;
}
export namespace SlimSubject {
}
