/**
 * Bangumi API
 * 你可以在 <https://api.bgm.tv/v0/oauth/> 生成一个 Access Token  ## 建议客户端开发者指定一个带有 APP 名称和版本的 User Agent，而非使用 HTTP 请求库默认的 UA  各种请求库的默认 UA 在未来可能会被禁用。 
 *
 * The version of the OpenAPI document: 2022-05-3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Collection } from './collection';
import { Images } from './images';
import { Item } from './item';
import { Rating } from './rating';
import { SubjectType } from './subjectType';
import { Tag } from './tag';


export interface Subject { 
    id: number;
    type: SubjectType;
    name: string;
    name_cn: string;
    summary: string;
    nsfw: boolean;
    locked: boolean;
    /**
     * air date in `YYYY-MM-DD` format
     */
    date?: string;
    /**
     * TV, Web, 欧美剧, PS4...
     */
    platform: string;
    images?: Images;
    infobox?: Array<Item>;
    /**
     * 书籍条目的册数，由旧服务端从wiki中解析
     */
    volumes: number;
    /**
     * 由旧服务端从wiki中解析，对于书籍条目为`话数`
     */
    eps: number;
    /**
     * 数据库中的章节数量
     */
    total_episodes: number;
    rating: Rating;
    collection: Collection;
    tags: Array<Tag>;
}
