/**
 * Bangumi API
 * 你可以在 <https://next.bgm.tv/demo/access-token> 生成一个 Access Token  ## [关于 User Agent](https://github.com/bangumi/api/blob/master/docs-raw/user%20agent.md)  如果你在使用中遇到了问题，请优先使用 GitHub issue 提交问题。在 bangumi 小组发帖可能无法得到及时反馈。 
 *
 * The version of the OpenAPI document: 2025-02-5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Collection } from './collection';
import { Images } from './images';
import { Item } from './item';
import { Rating } from './rating';
import { SubjectType } from './subjectType';
import { Tag } from './tag';


export interface Subject { 
    id: number;
    type: SubjectType;
    name: string;
    name_cn: string;
    summary: string;
    /**
     * 是否为书籍系列的主条目
     */
    series: boolean;
    nsfw: boolean;
    locked: boolean;
    /**
     * air date in `YYYY-MM-DD` format
     */
    date?: string;
    /**
     * TV, Web, 欧美剧, DLC...
     */
    platform: string;
    images: Images;
    infobox?: Array<Item>;
    /**
     * 书籍条目的册数，由旧服务端从wiki中解析
     */
    volumes: number;
    /**
     * 由旧服务端从wiki中解析，对于书籍条目为`话数`
     */
    eps: number;
    /**
     * 数据库中的章节数量
     */
    total_episodes: number;
    rating: Rating;
    collection: Collection;
    /**
     * 由维基人维护的 tag
     */
    meta_tags: Array<string>;
    tags: Array<Tag>;
}
export namespace Subject {
}
