/**
 * Bangumi API
 * 你可以在 <https://api.bgm.tv/v0/oauth/> 生成一个 Access Token  ## 建议客户端开发者指定一个带有 APP 名称和版本的 User Agent，而非使用 HTTP 请求库默认的 UA  各种请求库的默认 UA 在未来可能会被禁用。 
 *
 * The version of the OpenAPI document: 2022-04-20
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 条目类型 - `1` 为 书籍 - `2` 为 动画 - `3` 为 音乐 - `4` 为 游戏 - `6` 为 三次元  没有 `5`
 */
export type SubjectType1 = 1 | 2 | 3 | 4 | 6;

export const SubjectType1 = {
    NUMBER_1: 1 as SubjectType1,
    NUMBER_2: 2 as SubjectType1,
    NUMBER_3: 3 as SubjectType1,
    NUMBER_4: 4 as SubjectType1,
    NUMBER_6: 6 as SubjectType1
}
