/**
 * Bangumi API
 * 你可以在 <https://api.bgm.tv/v0/oauth/> 生成一个 Access Token  ## 建议客户端开发者指定一个带有 APP 名称和版本的 User Agent，而非使用 HTTP 请求库默认的 UA  各种请求库的默认 UA 在未来可能会被禁用。 
 *
 * The version of the OpenAPI document: 2022-04-20
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * An enumeration.
 */
export type UserGroup1 = 1 | 2 | 3 | 4 | 5 | 8 | 9 | 10 | 11;

export const UserGroup1 = {
    NUMBER_1: 1 as UserGroup1,
    NUMBER_2: 2 as UserGroup1,
    NUMBER_3: 3 as UserGroup1,
    NUMBER_4: 4 as UserGroup1,
    NUMBER_5: 5 as UserGroup1,
    NUMBER_8: 8 as UserGroup1,
    NUMBER_9: 9 as UserGroup1,
    NUMBER_10: 10 as UserGroup1,
    NUMBER_11: 11 as UserGroup1
}
