/**
 * Bangumi API
 * 你可以在 <https://next.bgm.tv/demo/access-token> 生成一个 Access Token  ## [关于 User Agent](https://github.com/bangumi/api/blob/master/docs-raw/user%20agent.md)  如果你在使用中遇到了问题，请优先使用 GitHub issue 提交问题。在 bangumi 小组发帖可能无法得到及时反馈。 
 *
 * The version of the OpenAPI document: 2025-02-5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SlimSubject } from './slimSubject';
import { SubjectCollectionType } from './subjectCollectionType';
import { SubjectType } from './subjectType';


export interface UserSubjectCollection { 
    subject_id: number;
    subject_type: SubjectType;
    rate: number;
    type: SubjectCollectionType;
    comment?: string;
    tags: Array<string>;
    ep_status: number;
    vol_status: number;
    /**
     * 本时间并不代表条目的收藏时间。修改评分，评价，章节观看状态等收藏信息时未更新此时间是一个 bug。请不要依赖此特性
     */
    updated_at: string;
    _private: boolean;
    subject?: SlimSubject;
}
export namespace UserSubjectCollection {
}
