/**
 * Bangumi API
 * 你可以在 <https://api.bgm.tv/v0/oauth/> 生成一个 Access Token  ## 建议客户端开发者指定一个带有 APP 名称和版本的 User Agent，而非使用 HTTP 请求库默认的 UA  各种请求库的默认 UA 在未来可能会被禁用。 
 *
 * The version of the OpenAPI document: 2022-04-23
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 用户组 - 1 = 管理员 - 2 = Bangumi 管理猿 - 3 = 天窗管理猿 - 4 = 禁言用户 - 5 = 禁止访问用户 - 8 = 人物管理猿 - 9 = 维基条目管理猿 - 10 = 用户 - 11 = 维基人
 */
export type UserGroup = 1 | 2 | 3 | 4 | 5 | 8 | 9 | 10 | 11;

export const UserGroup = {
    Admin: 1 as UserGroup,
    BangumiAdmin: 2 as UserGroup,
    DoujinAdmin: 3 as UserGroup,
    MutedUser: 4 as UserGroup,
    BlockedUser: 5 as UserGroup,
    PersonAdmin: 8 as UserGroup,
    WikiAdmin: 9 as UserGroup,
    User: 10 as UserGroup,
    WikiUser: 11 as UserGroup
}
