/* tslint:disable */
/* eslint-disable */
/**
 * Bangumi API
 * 你可以在 <https://api.bgm.tv/v0/oauth/> 生成一个 Access Token  ## 建议客户端开发者指定一个带有 APP 名称和版本的 User Agent，而非使用 HTTP 请求库默认的 UA  各种请求库的默认 UA 在未来可能会被禁用。 
 *
 * The version of the OpenAPI document: 2022-05-3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { BloodType } from './blood-type';
import { CharacterType } from './character-type';
import { PersonImages } from './person-images';
import { Stat } from './stat';

/**
 * 
 * @export
 * @interface CharacterDetail
 */
export interface CharacterDetail {
    /**
     * 
     * @type {number}
     * @memberof CharacterDetail
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof CharacterDetail
     */
    'name': string;
    /**
     * 角色，机体，舰船，组织...
     * @type {CharacterType}
     * @memberof CharacterDetail
     */
    'type': CharacterType;
    /**
     * object with some size of images, this object maybe `null`
     * @type {PersonImages}
     * @memberof CharacterDetail
     */
    'images'?: PersonImages;
    /**
     * 
     * @type {string}
     * @memberof CharacterDetail
     */
    'summary': string;
    /**
     * 
     * @type {boolean}
     * @memberof CharacterDetail
     */
    'locked': boolean;
    /**
     * server parsed infobox, a map from key to string or tuple null if server infobox is not valid
     * @type {Array<object>}
     * @memberof CharacterDetail
     */
    'infobox'?: Array<object>;
    /**
     * parsed from wiki, maybe null
     * @type {string}
     * @memberof CharacterDetail
     */
    'gender'?: string;
    /**
     * parsed from wiki, maybe null, `1, 2, 3, 4` for `A, B, AB, O`
     * @type {BloodType}
     * @memberof CharacterDetail
     */
    'blood_type'?: BloodType;
    /**
     * parsed from wiki, maybe `null`
     * @type {number}
     * @memberof CharacterDetail
     */
    'birth_year'?: number;
    /**
     * parsed from wiki, maybe `null`
     * @type {number}
     * @memberof CharacterDetail
     */
    'birth_mon'?: number;
    /**
     * parsed from wiki, maybe `null`
     * @type {number}
     * @memberof CharacterDetail
     */
    'birth_day'?: number;
    /**
     * 
     * @type {Stat}
     * @memberof CharacterDetail
     */
    'stat': Stat;
}

