/* tslint:disable */
/* eslint-disable */
/**
 * Bangumi API
 * 你可以在 <https://next.bgm.tv/demo/access-token> 生成一个 Access Token  ## [关于 User Agent](https://github.com/bangumi/api/blob/master/docs-raw/user%20agent.md)  如果你在使用中遇到了问题，请优先使用 GitHub issue 提交问题。在 bangumi 小组发帖可能无法得到及时反馈。 
 *
 * The version of the OpenAPI document: 2025-02-5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BloodType } from './blood-type';
// May contain unused imports in some cases
// @ts-ignore
import type { CharacterType } from './character-type';
// May contain unused imports in some cases
// @ts-ignore
import type { PersonImages } from './person-images';
// May contain unused imports in some cases
// @ts-ignore
import type { Stat } from './stat';

/**
 * 
 * @export
 * @interface Character
 */
export interface Character {
    /**
     * 
     * @type {number}
     * @memberof Character
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof Character
     */
    'name': string;
    /**
     * 角色，机体，舰船，组织...
     * @type {CharacterType}
     * @memberof Character
     */
    'type': CharacterType;
    /**
     * object with some size of images, this object maybe `null`
     * @type {PersonImages}
     * @memberof Character
     */
    'images'?: PersonImages;
    /**
     * 
     * @type {string}
     * @memberof Character
     */
    'summary': string;
    /**
     * 
     * @type {boolean}
     * @memberof Character
     */
    'locked': boolean;
    /**
     * server parsed infobox, a map from key to string or tuple null if server infobox is not valid
     * @type {Array<object>}
     * @memberof Character
     */
    'infobox'?: Array<object>;
    /**
     * parsed from wiki, maybe null
     * @type {string}
     * @memberof Character
     */
    'gender'?: string;
    /**
     * parsed from wiki, maybe null, `1, 2, 3, 4` for `A, B, AB, O`
     * @type {BloodType}
     * @memberof Character
     */
    'blood_type'?: BloodType;
    /**
     * parsed from wiki, maybe `null`
     * @type {number}
     * @memberof Character
     */
    'birth_year'?: number;
    /**
     * parsed from wiki, maybe `null`
     * @type {number}
     * @memberof Character
     */
    'birth_mon'?: number;
    /**
     * parsed from wiki, maybe `null`
     * @type {number}
     * @memberof Character
     */
    'birth_day'?: number;
    /**
     * 
     * @type {Stat}
     * @memberof Character
     */
    'stat': Stat;
}



