/* tslint:disable */
/* eslint-disable */
/**
 * Bangumi API
 * 你可以在 <https://api.bgm.tv/v0/oauth/> 生成一个 Access Token  ## 建议客户端开发者指定一个带有 APP 名称和版本的 User Agent，而非使用 HTTP 请求库默认的 UA  各种请求库的默认 UA 在未来可能会被禁用。 
 *
 * The version of the OpenAPI document: 2022-05-3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CollectionStatusId } from './collection-status-id';
import { CollectionStatusName } from './collection-status-name';
import { CollectionStatusType } from './collection-status-type';

/**
 * 收藏状态 - 1 = wish = 想做 - 2 = collect = 做过 - 3 = do = 在做 - 4 = on_hold = 搁置 - 5 = dropped = 抛弃
 * @export
 * @interface CollectionStatus
 */
export interface CollectionStatus {
    /**
     * 
     * @type {CollectionStatusId}
     * @memberof CollectionStatus
     */
    'id'?: CollectionStatusId;
    /**
     * 
     * @type {CollectionStatusType}
     * @memberof CollectionStatus
     */
    'type'?: CollectionStatusType;
    /**
     * 
     * @type {CollectionStatusName}
     * @memberof CollectionStatus
     */
    'name'?: CollectionStatusName;
}

