/* tslint:disable */
/* eslint-disable */
/**
 * Bangumi API
 * 你可以在 <https://next.bgm.tv/demo/access-token> 生成一个 Access Token  ## [关于 User Agent](https://github.com/bangumi/api/blob/master/docs-raw/user%20agent.md)  如果你在使用中遇到了问题，请优先使用 GitHub issue 提交问题。在 bangumi 小组发帖可能无法得到及时反馈。 
 *
 * The version of the OpenAPI document: 2025-02-5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Creator } from './creator';

/**
 * 
 * @export
 * @interface DetailedRevision
 */
export interface DetailedRevision {
    /**
     * 
     * @type {number}
     * @memberof DetailedRevision
     */
    'id': number;
    /**
     * 
     * @type {number}
     * @memberof DetailedRevision
     */
    'type': number;
    /**
     * 
     * @type {Creator}
     * @memberof DetailedRevision
     */
    'creator'?: Creator;
    /**
     * 
     * @type {string}
     * @memberof DetailedRevision
     */
    'summary': string;
    /**
     * 
     * @type {string}
     * @memberof DetailedRevision
     */
    'created_at': string;
    /**
     * 编辑修改内容，响应类型不固定
     * @type {object}
     * @memberof DetailedRevision
     */
    'data'?: object;
}

