/* tslint:disable */
/* eslint-disable */
/**
 * Bangumi API
 * 你可以在 <https://next.bgm.tv/demo/access-token> 生成一个 Access Token  ## [关于 User Agent](https://github.com/bangumi/api/blob/master/docs-raw/user%20agent.md)  如果你在使用中遇到了问题，请优先使用 GitHub issue 提交问题。在 bangumi 小组发帖可能无法得到及时反馈。 
 *
 * The version of the OpenAPI document: 2025-02-5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { EpType } from './ep-type';

/**
 * 
 * @export
 * @interface EpisodeDetail
 */
export interface EpisodeDetail {
    /**
     * 
     * @type {number}
     * @memberof EpisodeDetail
     */
    'id': number;
    /**
     * 
     * @type {EpType}
     * @memberof EpisodeDetail
     */
    'type': EpType;
    /**
     * 
     * @type {string}
     * @memberof EpisodeDetail
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof EpisodeDetail
     */
    'name_cn': string;
    /**
     * 同类条目的排序和集数
     * @type {number}
     * @memberof EpisodeDetail
     */
    'sort': number;
    /**
     * 条目内的集数, 从`1`开始。非本篇剧集的此字段无意义
     * @type {number}
     * @memberof EpisodeDetail
     */
    'ep'?: number;
    /**
     * 
     * @type {string}
     * @memberof EpisodeDetail
     */
    'airdate': string;
    /**
     * 
     * @type {number}
     * @memberof EpisodeDetail
     */
    'comment': number;
    /**
     * 
     * @type {string}
     * @memberof EpisodeDetail
     */
    'duration': string;
    /**
     * 简介
     * @type {string}
     * @memberof EpisodeDetail
     */
    'desc': string;
    /**
     * 音乐曲目的碟片数
     * @type {number}
     * @memberof EpisodeDetail
     */
    'disc': number;
    /**
     * 
     * @type {number}
     * @memberof EpisodeDetail
     */
    'subject_id': number;
}



