/* tslint:disable */
/* eslint-disable */
/**
 * Bangumi API
 * 你可以在 <https://next.bgm.tv/demo/access-token> 生成一个 Access Token  ## [关于 User Agent](https://github.com/bangumi/api/blob/master/docs-raw/user%20agent.md)  如果你在使用中遇到了问题，请优先使用 GitHub issue 提交问题。在 bangumi 小组发帖可能无法得到及时反馈。 
 *
 * The version of the OpenAPI document: 2025-02-5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Episode
 */
export interface Episode {
    /**
     * 
     * @type {number}
     * @memberof Episode
     */
    'id': number;
    /**
     * `0` 本篇，`1` SP，`2` OP，`3` ED
     * @type {number}
     * @memberof Episode
     */
    'type': number;
    /**
     * 
     * @type {string}
     * @memberof Episode
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof Episode
     */
    'name_cn': string;
    /**
     * 同类条目的排序和集数
     * @type {number}
     * @memberof Episode
     */
    'sort': number;
    /**
     * 条目内的集数, 从`1`开始。非本篇剧集的此字段无意义
     * @type {number}
     * @memberof Episode
     */
    'ep'?: number;
    /**
     * 
     * @type {string}
     * @memberof Episode
     */
    'airdate': string;
    /**
     * 
     * @type {number}
     * @memberof Episode
     */
    'comment': number;
    /**
     * 维基人填写的原始时长
     * @type {string}
     * @memberof Episode
     */
    'duration': string;
    /**
     * 简介
     * @type {string}
     * @memberof Episode
     */
    'desc': string;
    /**
     * 音乐曲目的碟片数
     * @type {number}
     * @memberof Episode
     */
    'disc': number;
    /**
     * 服务器解析的时长，无法解析时为 `0`
     * @type {number}
     * @memberof Episode
     */
    'duration_seconds'?: number;
}

