/* tslint:disable */
/* eslint-disable */
/**
 * Bangumi API
 * 你可以在 <https://api.bgm.tv/v0/oauth/> 生成一个 Access Token  ## 建议客户端开发者指定一个带有 APP 名称和版本的 User Agent，而非使用 HTTP 请求库默认的 UA  各种请求库的默认 UA 在未来可能会被禁用。 
 *
 * The version of the OpenAPI document: 2022-05-3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Images } from './images';
import { Item } from './item';

/**
 * 同名字段意义同<a href=\"#model-Subject\">Subject</a>
 * @export
 * @interface IndexSubject
 */
export interface IndexSubject {
    /**
     * 
     * @type {number}
     * @memberof IndexSubject
     */
    'id': number;
    /**
     * 
     * @type {number}
     * @memberof IndexSubject
     */
    'type': number;
    /**
     * 
     * @type {string}
     * @memberof IndexSubject
     */
    'name': string;
    /**
     * 
     * @type {Images}
     * @memberof IndexSubject
     */
    'images'?: Images;
    /**
     * 
     * @type {Array<Item>}
     * @memberof IndexSubject
     */
    'infobox'?: Array<Item>;
    /**
     * 
     * @type {string}
     * @memberof IndexSubject
     */
    'date'?: string;
    /**
     * 
     * @type {string}
     * @memberof IndexSubject
     */
    'comment': string;
    /**
     * 
     * @type {string}
     * @memberof IndexSubject
     */
    'added_at': string;
}

