/* tslint:disable */
/* eslint-disable */
/**
 * Bangumi API
 * 你可以在 <https://api.bgm.tv/v0/oauth/> 生成一个 Access Token  ## 建议客户端开发者指定一个带有 APP 名称和版本的 User Agent，而非使用 HTTP 请求库默认的 UA  各种请求库的默认 UA 在未来可能会被禁用。 
 *
 * The version of the OpenAPI document: 2022-05-3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { SubjectType } from './subject-type';
import { SubjectTypeName } from './subject-type-name';
import { UserUsernameCollectionsStatusCollects } from './user-username-collections-status-collects';

/**
 * 
 * @export
 * @interface InlineResponse2001
 */
export interface InlineResponse2001 {
    /**
     * 
     * @type {SubjectType}
     * @memberof InlineResponse2001
     */
    'type'?: SubjectType;
    /**
     * 
     * @type {SubjectTypeName}
     * @memberof InlineResponse2001
     */
    'name'?: SubjectTypeName;
    /**
     * 条目类型中文名
     * @type {string}
     * @memberof InlineResponse2001
     */
    'name_cn'?: string;
    /**
     * 收藏列表
     * @type {Array<UserUsernameCollectionsStatusCollects>}
     * @memberof InlineResponse2001
     */
    'collects'?: Array<UserUsernameCollectionsStatusCollects>;
}

