/* tslint:disable */
/* eslint-disable */
/**
 * Bangumi API
 * 你可以在 <https://next.bgm.tv/demo/access-token> 生成一个 Access Token  ## [关于 User Agent](https://github.com/bangumi/api/blob/master/docs-raw/user%20agent.md)  如果你在使用中遇到了问题，请优先使用 GitHub issue 提交问题。在 bangumi 小组发帖可能无法得到及时反馈。 
 *
 * The version of the OpenAPI document: 2025-02-5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { LegacySubjectSmallCollection } from './legacy-subject-small-collection';
// May contain unused imports in some cases
// @ts-ignore
import type { LegacySubjectSmallImages } from './legacy-subject-small-images';
// May contain unused imports in some cases
// @ts-ignore
import type { LegacySubjectSmallRating } from './legacy-subject-small-rating';

/**
 * 
 * @export
 * @interface LegacySubjectSmall
 */
export interface LegacySubjectSmall {
    /**
     * 条目 ID
     * @type {number}
     * @memberof LegacySubjectSmall
     */
    'id'?: number;
    /**
     * 条目地址
     * @type {string}
     * @memberof LegacySubjectSmall
     */
    'url'?: string;
    /**
     * 条目类型 - `1` 为 书籍 - `2` 为 动画 - `3` 为 音乐 - `4` 为 游戏 - `6` 为 三次元  没有 `5`
     * @type {number}
     * @memberof LegacySubjectSmall
     */
    'type'?: LegacySubjectSmallTypeEnum;
    /**
     * 条目名称
     * @type {string}
     * @memberof LegacySubjectSmall
     */
    'name'?: string;
    /**
     * 条目中文名称
     * @type {string}
     * @memberof LegacySubjectSmall
     */
    'name_cn'?: string;
    /**
     * 剧情简介
     * @type {string}
     * @memberof LegacySubjectSmall
     */
    'summary'?: string;
    /**
     * 放送开始日期
     * @type {string}
     * @memberof LegacySubjectSmall
     */
    'air_date'?: string;
    /**
     * 放送星期
     * @type {number}
     * @memberof LegacySubjectSmall
     */
    'air_weekday'?: number;
    /**
     * 
     * @type {LegacySubjectSmallImages}
     * @memberof LegacySubjectSmall
     */
    'images'?: LegacySubjectSmallImages;
    /**
     * 话数
     * @type {number}
     * @memberof LegacySubjectSmall
     */
    'eps'?: number;
    /**
     * 话数
     * @type {number}
     * @memberof LegacySubjectSmall
     */
    'eps_count'?: number;
    /**
     * 
     * @type {LegacySubjectSmallRating}
     * @memberof LegacySubjectSmall
     */
    'rating'?: LegacySubjectSmallRating;
    /**
     * 排名
     * @type {number}
     * @memberof LegacySubjectSmall
     */
    'rank'?: number;
    /**
     * 
     * @type {LegacySubjectSmallCollection}
     * @memberof LegacySubjectSmall
     */
    'collection'?: LegacySubjectSmallCollection;
}

export const LegacySubjectSmallTypeEnum = {
    Book: 1,
    Anime: 2,
    Music: 3,
    Game: 4,
    Real: 6
} as const;

export type LegacySubjectSmallTypeEnum = typeof LegacySubjectSmallTypeEnum[keyof typeof LegacySubjectSmallTypeEnum];


