/* tslint:disable */
/* eslint-disable */
/**
 * Bangumi API
 * 你可以在 <https://next.bgm.tv/demo/access-token> 生成一个 Access Token  ## [关于 User Agent](https://github.com/bangumi/api/blob/master/docs-raw/user%20agent.md)  如果你在使用中遇到了问题，请优先使用 GitHub issue 提交问题。在 bangumi 小组发帖可能无法得到及时反馈。 
 *
 * The version of the OpenAPI document: 2025-02-5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { LegacyEpisodeType } from './legacy-episode-type';

/**
 * 章节信息
 * @export
 * @interface LegacyEpisode
 */
export interface LegacyEpisode {
    /**
     * 章节 ID
     * @type {number}
     * @memberof LegacyEpisode
     */
    'id'?: number;
    /**
     * 章节地址
     * @type {string}
     * @memberof LegacyEpisode
     */
    'url'?: string;
    /**
     * 
     * @type {LegacyEpisodeType}
     * @memberof LegacyEpisode
     */
    'type'?: LegacyEpisodeType;
    /**
     * 集数
     * @type {number}
     * @memberof LegacyEpisode
     */
    'sort'?: number;
    /**
     * 标题
     * @type {string}
     * @memberof LegacyEpisode
     */
    'name'?: string;
    /**
     * 简体中文标题
     * @type {string}
     * @memberof LegacyEpisode
     */
    'name_cn'?: string;
    /**
     * 时长
     * @type {string}
     * @memberof LegacyEpisode
     */
    'duration'?: string;
    /**
     * 放送日期
     * @type {string}
     * @memberof LegacyEpisode
     */
    'airdate'?: string;
    /**
     * 回复数量
     * @type {number}
     * @memberof LegacyEpisode
     */
    'comment'?: number;
    /**
     * 简介
     * @type {string}
     * @memberof LegacyEpisode
     */
    'desc'?: string;
    /**
     * 放送状态 <br> Air = 已放送 <br> Today = 正在放送 <br> NA = 未放送
     * @type {string}
     * @memberof LegacyEpisode
     */
    'status'?: LegacyEpisodeStatusEnum;
}

export const LegacyEpisodeStatusEnum = {
    Air: 'Air',
    Today: 'Today',
    Na: 'NA'
} as const;

export type LegacyEpisodeStatusEnum = typeof LegacyEpisodeStatusEnum[keyof typeof LegacyEpisodeStatusEnum];


