/* tslint:disable */
/* eslint-disable */
/**
 * Bangumi API
 * 你可以在 <https://api.bgm.tv/v0/oauth/> 生成一个 Access Token  ## 建议客户端开发者指定一个带有 APP 名称和版本的 User Agent，而非使用 HTTP 请求库默认的 UA  各种请求库的默认 UA 在未来可能会被禁用。 
 *
 * The version of the OpenAPI document: 2022-05-3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { BloodType } from './blood-type';
import { PersonCareer } from './person-career';
import { PersonImages } from './person-images';
import { PersonType } from './person-type';
import { Stat } from './stat';

/**
 * 
 * @export
 * @interface PersonDetail
 */
export interface PersonDetail {
    /**
     * 
     * @type {number}
     * @memberof PersonDetail
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof PersonDetail
     */
    'name': string;
    /**
     * `1`, `2`, `3` 表示 `个人`, `公司`, `组合`
     * @type {PersonType}
     * @memberof PersonDetail
     */
    'type': PersonType;
    /**
     * 
     * @type {Array<PersonCareer>}
     * @memberof PersonDetail
     */
    'career': Array<PersonCareer>;
    /**
     * object with some size of images, this object maybe `null`
     * @type {PersonImages}
     * @memberof PersonDetail
     */
    'images'?: PersonImages;
    /**
     * 
     * @type {string}
     * @memberof PersonDetail
     */
    'summary': string;
    /**
     * 
     * @type {boolean}
     * @memberof PersonDetail
     */
    'locked': boolean;
    /**
     * currently it\'s latest user comment time, it will be replaced by wiki modified date in the future
     * @type {string}
     * @memberof PersonDetail
     */
    'last_modified': string;
    /**
     * server parsed infobox, a map from key to string or tuple null if server infobox is not valid
     * @type {Array<object>}
     * @memberof PersonDetail
     */
    'infobox'?: Array<object>;
    /**
     * parsed from wiki, maybe null
     * @type {string}
     * @memberof PersonDetail
     */
    'gender'?: string;
    /**
     * parsed from wiki, maybe null, `1, 2, 3, 4` for `A, B, AB, O`
     * @type {BloodType}
     * @memberof PersonDetail
     */
    'blood_type'?: BloodType;
    /**
     * parsed from wiki, maybe `null`
     * @type {number}
     * @memberof PersonDetail
     */
    'birth_year'?: number;
    /**
     * parsed from wiki, maybe `null`
     * @type {number}
     * @memberof PersonDetail
     */
    'birth_mon'?: number;
    /**
     * parsed from wiki, maybe `null`
     * @type {number}
     * @memberof PersonDetail
     */
    'birth_day'?: number;
    /**
     * 
     * @type {Stat}
     * @memberof PersonDetail
     */
    'stat': Stat;
}

