/* tslint:disable */
/* eslint-disable */
/**
 * Bangumi API
 * 你可以在 <https://next.bgm.tv/demo/access-token> 生成一个 Access Token  ## [关于 User Agent](https://github.com/bangumi/api/blob/master/docs-raw/user%20agent.md)  如果你在使用中遇到了问题，请优先使用 GitHub issue 提交问题。在 bangumi 小组发帖可能无法得到及时反馈。 
 *
 * The version of the OpenAPI document: 2025-02-5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BloodType } from './blood-type';
// May contain unused imports in some cases
// @ts-ignore
import type { PersonCareer } from './person-career';
// May contain unused imports in some cases
// @ts-ignore
import type { PersonImages } from './person-images';
// May contain unused imports in some cases
// @ts-ignore
import type { PersonType } from './person-type';
// May contain unused imports in some cases
// @ts-ignore
import type { Stat } from './stat';

/**
 * 
 * @export
 * @interface PersonDetail
 */
export interface PersonDetail {
    /**
     * 
     * @type {number}
     * @memberof PersonDetail
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof PersonDetail
     */
    'name': string;
    /**
     * `1`, `2`, `3` 表示 `个人`, `公司`, `组合`
     * @type {PersonType}
     * @memberof PersonDetail
     */
    'type': PersonType;
    /**
     * 
     * @type {Array<PersonCareer>}
     * @memberof PersonDetail
     */
    'career': Array<PersonCareer>;
    /**
     * object with some size of images, this object maybe `null`
     * @type {PersonImages}
     * @memberof PersonDetail
     */
    'images'?: PersonImages;
    /**
     * 
     * @type {string}
     * @memberof PersonDetail
     */
    'summary': string;
    /**
     * 
     * @type {boolean}
     * @memberof PersonDetail
     */
    'locked': boolean;
    /**
     * currently it\'s latest user comment time, it will be replaced by wiki modified date in the future
     * @type {string}
     * @memberof PersonDetail
     */
    'last_modified': string;
    /**
     * server parsed infobox, a map from key to string or tuple null if server infobox is not valid
     * @type {Array<object>}
     * @memberof PersonDetail
     */
    'infobox'?: Array<object>;
    /**
     * parsed from wiki, maybe null
     * @type {string}
     * @memberof PersonDetail
     */
    'gender'?: string;
    /**
     * parsed from wiki, maybe null, `1, 2, 3, 4` for `A, B, AB, O`
     * @type {BloodType}
     * @memberof PersonDetail
     */
    'blood_type'?: BloodType;
    /**
     * parsed from wiki, maybe `null`
     * @type {number}
     * @memberof PersonDetail
     */
    'birth_year'?: number;
    /**
     * parsed from wiki, maybe `null`
     * @type {number}
     * @memberof PersonDetail
     */
    'birth_mon'?: number;
    /**
     * parsed from wiki, maybe `null`
     * @type {number}
     * @memberof PersonDetail
     */
    'birth_day'?: number;
    /**
     * 
     * @type {Stat}
     * @memberof PersonDetail
     */
    'stat': Stat;
}



