/* tslint:disable */
/* eslint-disable */
/**
 * Bangumi API
 * 你可以在 <https://next.bgm.tv/demo/access-token> 生成一个 Access Token  ## [关于 User Agent](https://github.com/bangumi/api/blob/master/docs-raw/user%20agent.md)  如果你在使用中遇到了问题，请优先使用 GitHub issue 提交问题。在 bangumi 小组发帖可能无法得到及时反馈。 
 *
 * The version of the OpenAPI document: 2025-02-5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PersonCareer } from './person-career';
// May contain unused imports in some cases
// @ts-ignore
import type { PersonImages } from './person-images';
// May contain unused imports in some cases
// @ts-ignore
import type { PersonType } from './person-type';

/**
 * 
 * @export
 * @interface Person
 */
export interface Person {
    /**
     * 
     * @type {number}
     * @memberof Person
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof Person
     */
    'name': string;
    /**
     * `1`, `2`, `3` 表示 `个人`, `公司`, `组合`
     * @type {PersonType}
     * @memberof Person
     */
    'type': PersonType;
    /**
     * 
     * @type {Array<PersonCareer>}
     * @memberof Person
     */
    'career': Array<PersonCareer>;
    /**
     * object with some size of images, this object maybe `null`
     * @type {PersonImages}
     * @memberof Person
     */
    'images'?: PersonImages;
    /**
     * 
     * @type {string}
     * @memberof Person
     */
    'short_summary': string;
    /**
     * 
     * @type {boolean}
     * @memberof Person
     */
    'locked': boolean;
}



