/* tslint:disable */
/* eslint-disable */
/**
 * Bangumi API
 * 你可以在 <https://api.bgm.tv/v0/oauth/> 生成一个 Access Token  ## 建议客户端开发者指定一个带有 APP 名称和版本的 User Agent，而非使用 HTTP 请求库默认的 UA  各种请求库的默认 UA 在未来可能会被禁用。 
 *
 * The version of the OpenAPI document: 2022-05-3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Images } from './images';

/**
 * 
 * @export
 * @interface PolApiV0ModelsSubjectRelatedSubject
 */
export interface PolApiV0ModelsSubjectRelatedSubject {
    /**
     * 
     * @type {number}
     * @memberof PolApiV0ModelsSubjectRelatedSubject
     */
    'id': number;
    /**
     * 
     * @type {number}
     * @memberof PolApiV0ModelsSubjectRelatedSubject
     */
    'type': number;
    /**
     * 
     * @type {string}
     * @memberof PolApiV0ModelsSubjectRelatedSubject
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof PolApiV0ModelsSubjectRelatedSubject
     */
    'name_cn': string;
    /**
     * 
     * @type {Images}
     * @memberof PolApiV0ModelsSubjectRelatedSubject
     */
    'images'?: Images;
    /**
     * 
     * @type {string}
     * @memberof PolApiV0ModelsSubjectRelatedSubject
     */
    'relation': string;
}

