/* tslint:disable */
/* eslint-disable */
/**
 * Bangumi API
 * 你可以在 <https://api.bgm.tv/v0/oauth/> 生成一个 Access Token  ## 建议客户端开发者指定一个带有 APP 名称和版本的 User Agent，而非使用 HTTP 请求库默认的 UA  各种请求库的默认 UA 在未来可能会被禁用。 
 *
 * The version of the OpenAPI document: 2022-05-3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CharacterType } from './character-type';
import { Person } from './person';
import { PersonImages } from './person-images';

/**
 * 
 * @export
 * @interface RelatedCharacter
 */
export interface RelatedCharacter {
    /**
     * 
     * @type {number}
     * @memberof RelatedCharacter
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof RelatedCharacter
     */
    'name': string;
    /**
     * 角色，机体，舰船，组织...
     * @type {CharacterType}
     * @memberof RelatedCharacter
     */
    'type': CharacterType;
    /**
     * object with some size of images, this object maybe `null`
     * @type {PersonImages}
     * @memberof RelatedCharacter
     */
    'images'?: PersonImages;
    /**
     * 
     * @type {string}
     * @memberof RelatedCharacter
     */
    'relation': string;
    /**
     * 演员列表
     * @type {Array<Person>}
     * @memberof RelatedCharacter
     */
    'actors'?: Array<Person>;
}

