/* tslint:disable */
/* eslint-disable */
/**
 * Bangumi API
 * 你可以在 <https://next.bgm.tv/demo/access-token> 生成一个 Access Token  ## [关于 User Agent](https://github.com/bangumi/api/blob/master/docs-raw/user%20agent.md)  如果你在使用中遇到了问题，请优先使用 GitHub issue 提交问题。在 bangumi 小组发帖可能无法得到及时反馈。 
 *
 * The version of the OpenAPI document: 2025-02-5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Images } from './images';
// May contain unused imports in some cases
// @ts-ignore
import type { SubjectType } from './subject-type';
// May contain unused imports in some cases
// @ts-ignore
import type { Tag } from './tag';

/**
 * 
 * @export
 * @interface SlimSubject
 */
export interface SlimSubject {
    /**
     * 
     * @type {number}
     * @memberof SlimSubject
     */
    'id': number;
    /**
     * 
     * @type {SubjectType}
     * @memberof SlimSubject
     */
    'type': SubjectType;
    /**
     * 
     * @type {string}
     * @memberof SlimSubject
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof SlimSubject
     */
    'name_cn': string;
    /**
     * 截短后的条目描述。
     * @type {string}
     * @memberof SlimSubject
     */
    'short_summary': string;
    /**
     * air date in `YYYY-MM-DD` format
     * @type {string}
     * @memberof SlimSubject
     */
    'date'?: string;
    /**
     * 
     * @type {Images}
     * @memberof SlimSubject
     */
    'images': Images;
    /**
     * 书籍条目的册数，由旧服务端从wiki中解析
     * @type {number}
     * @memberof SlimSubject
     */
    'volumes': number;
    /**
     * 由旧服务端从wiki中解析，对于书籍条目为`话数`
     * @type {number}
     * @memberof SlimSubject
     */
    'eps': number;
    /**
     * 收藏人数
     * @type {number}
     * @memberof SlimSubject
     */
    'collection_total': number;
    /**
     * 分数
     * @type {number}
     * @memberof SlimSubject
     */
    'score': number;
    /**
     * 排名
     * @type {number}
     * @memberof SlimSubject
     */
    'rank': number;
    /**
     * 前 10 个 tag
     * @type {Array<Tag>}
     * @memberof SlimSubject
     */
    'tags': Array<Tag>;
}



