/* tslint:disable */
/* eslint-disable */
/**
 * Bangumi API
 * 你可以在 <https://api.bgm.tv/v0/oauth/> 生成一个 Access Token  ## 建议客户端开发者指定一个带有 APP 名称和版本的 User Agent，而非使用 HTTP 请求库默认的 UA  各种请求库的默认 UA 在未来可能会被禁用。 
 *
 * The version of the OpenAPI document: 2022-05-3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 响应状态（HTTP 状态码都为 200）
 * @export
 * @interface StatusCode
 */
export interface StatusCode {
    /**
     * 当前请求的地址
     * @type {string}
     * @memberof StatusCode
     */
    'request'?: string;
    /**
     * 状态码 <br> 200 OK <br> 202 Accepted <br> 304 Not Modified <br> 30401 Not Modified: Collection already exists <br> 400 Bad Request <br> 40001 Error: Nothing found with that ID <br> 401 Unauthorized <br> 40101 Error: Auth failed over 5 times <br> 40102 Error: Username is not an Email address <br> 405 Method Not Allowed <br> 404 Not Found
     * @type {number}
     * @memberof StatusCode
     */
    'code'?: StatusCodeCodeEnum;
    /**
     * 状态信息
     * @type {string}
     * @memberof StatusCode
     */
    'error'?: string;
}

export const StatusCodeCodeEnum = {
    NUMBER_200: 200,
    NUMBER_202: 202,
    NUMBER_304: 304,
    NUMBER_30401: 30401,
    NUMBER_400: 400,
    NUMBER_40001: 40001,
    NUMBER_401: 401,
    NUMBER_40101: 40101,
    NUMBER_40102: 40102,
    NUMBER_405: 405,
    NUMBER_404: 404
} as const;

export type StatusCodeCodeEnum = typeof StatusCodeCodeEnum[keyof typeof StatusCodeCodeEnum];


