/* tslint:disable */
/* eslint-disable */
/**
 * Bangumi API
 * 你可以在 <https://api.bgm.tv/v0/oauth/> 生成一个 Access Token  ## 建议客户端开发者指定一个带有 APP 名称和版本的 User Agent，而非使用 HTTP 请求库默认的 UA  各种请求库的默认 UA 在未来可能会被禁用。 
 *
 * The version of the OpenAPI document: 2022-05-3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Collection } from './collection';
import { Images } from './images';
import { Item } from './item';
import { Rating } from './rating';
import { SubjectType } from './subject-type';
import { Tag } from './tag';

/**
 * 
 * @export
 * @interface Subject
 */
export interface Subject {
    /**
     * 
     * @type {number}
     * @memberof Subject
     */
    'id': number;
    /**
     * 
     * @type {SubjectType}
     * @memberof Subject
     */
    'type': SubjectType;
    /**
     * 
     * @type {string}
     * @memberof Subject
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof Subject
     */
    'name_cn': string;
    /**
     * 
     * @type {string}
     * @memberof Subject
     */
    'summary': string;
    /**
     * 
     * @type {boolean}
     * @memberof Subject
     */
    'nsfw': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Subject
     */
    'locked': boolean;
    /**
     * air date in `YYYY-MM-DD` format
     * @type {string}
     * @memberof Subject
     */
    'date'?: string;
    /**
     * TV, Web, 欧美剧, PS4...
     * @type {string}
     * @memberof Subject
     */
    'platform': string;
    /**
     * 
     * @type {Images}
     * @memberof Subject
     */
    'images'?: Images;
    /**
     * 
     * @type {Array<Item>}
     * @memberof Subject
     */
    'infobox'?: Array<Item>;
    /**
     * 书籍条目的册数，由旧服务端从wiki中解析
     * @type {number}
     * @memberof Subject
     */
    'volumes': number;
    /**
     * 由旧服务端从wiki中解析，对于书籍条目为`话数`
     * @type {number}
     * @memberof Subject
     */
    'eps': number;
    /**
     * 数据库中的章节数量
     * @type {number}
     * @memberof Subject
     */
    'total_episodes': number;
    /**
     * 
     * @type {Rating}
     * @memberof Subject
     */
    'rating': Rating;
    /**
     * 
     * @type {Collection}
     * @memberof Subject
     */
    'collection': Collection;
    /**
     * 
     * @type {Array<Tag>}
     * @memberof Subject
     */
    'tags': Array<Tag>;
}

