/* tslint:disable */
/* eslint-disable */
/**
 * Bangumi API
 * 你可以在 <https://next.bgm.tv/demo/access-token> 生成一个 Access Token  ## [关于 User Agent](https://github.com/bangumi/api/blob/master/docs-raw/user%20agent.md)  如果你在使用中遇到了问题，请优先使用 GitHub issue 提交问题。在 bangumi 小组发帖可能无法得到及时反馈。 
 *
 * The version of the OpenAPI document: 2025-02-5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 游戏类型 - `0` 为 其他 - `4001` 为 游戏 - `4002` 为 软件 - `4003` 为 扩展包 - `4005` 为 桌游
 * @export
 * @enum {string}
 */

export const SubjectGameCategory = {
    Other: 0,
    Games: 4001,
    Software: 4003,
    DLC: 4002,
    Tabletop: 4005
} as const;

export type SubjectGameCategory = typeof SubjectGameCategory[keyof typeof SubjectGameCategory];



