/* tslint:disable */
/* eslint-disable */
/**
 * Bangumi API
 * 你可以在 <https://next.bgm.tv/demo/access-token> 生成一个 Access Token  ## [关于 User Agent](https://github.com/bangumi/api/blob/master/docs-raw/user%20agent.md)  如果你在使用中遇到了问题，请优先使用 GitHub issue 提交问题。在 bangumi 小组发帖可能无法得到及时反馈。 
 *
 * The version of the OpenAPI document: 2025-02-5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SubjectRevisionData
 */
export interface SubjectRevisionData {
    /**
     * 
     * @type {number}
     * @memberof SubjectRevisionData
     */
    'field_eps': number;
    /**
     * 
     * @type {string}
     * @memberof SubjectRevisionData
     */
    'field_infobox': string;
    /**
     * 
     * @type {string}
     * @memberof SubjectRevisionData
     */
    'field_summary': string;
    /**
     * 
     * @type {string}
     * @memberof SubjectRevisionData
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof SubjectRevisionData
     */
    'name_cn': string;
    /**
     * 
     * @type {number}
     * @memberof SubjectRevisionData
     */
    'platform': number;
    /**
     * 
     * @type {number}
     * @memberof SubjectRevisionData
     */
    'subject_id': number;
    /**
     * 
     * @type {number}
     * @memberof SubjectRevisionData
     */
    'type': number;
    /**
     * 
     * @type {number}
     * @memberof SubjectRevisionData
     */
    'type_id': number;
    /**
     * 
     * @type {string}
     * @memberof SubjectRevisionData
     */
    'vote_field': string;
}

