/* tslint:disable */
/* eslint-disable */
/**
 * Bangumi API
 * 你可以在 <https://api.bgm.tv/v0/oauth/> 生成一个 Access Token  ## 建议客户端开发者指定一个带有 APP 名称和版本的 User Agent，而非使用 HTTP 请求库默认的 UA  各种请求库的默认 UA 在未来可能会被禁用。 
 *
 * The version of the OpenAPI document: 2022-05-3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CollectionType } from './collection-type';
import { SubjectType } from './subject-type';

/**
 * 
 * @export
 * @interface UserCollection
 */
export interface UserCollection {
    /**
     * 
     * @type {number}
     * @memberof UserCollection
     */
    'subject_id': number;
    /**
     * 
     * @type {SubjectType}
     * @memberof UserCollection
     */
    'subject_type': SubjectType;
    /**
     * 
     * @type {number}
     * @memberof UserCollection
     */
    'rate': number;
    /**
     * 
     * @type {CollectionType}
     * @memberof UserCollection
     */
    'type': CollectionType;
    /**
     * 
     * @type {string}
     * @memberof UserCollection
     */
    'comment'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof UserCollection
     */
    'tags': Array<string>;
    /**
     * 
     * @type {number}
     * @memberof UserCollection
     */
    'ep_status': number;
    /**
     * 
     * @type {number}
     * @memberof UserCollection
     */
    'vol_status': number;
    /**
     * 
     * @type {string}
     * @memberof UserCollection
     */
    'updated_at': string;
    /**
     * 
     * @type {boolean}
     * @memberof UserCollection
     */
    'private': boolean;
}

