/* tslint:disable */
/* eslint-disable */
/**
 * Bangumi API
 * 你可以在 <https://next.bgm.tv/demo/access-token> 生成一个 Access Token  ## [关于 User Agent](https://github.com/bangumi/api/blob/master/docs-raw/user%20agent.md)  如果你在使用中遇到了问题，请优先使用 GitHub issue 提交问题。在 bangumi 小组发帖可能无法得到及时反馈。 
 *
 * The version of the OpenAPI document: 2025-02-5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SubjectCollectionType } from './subject-collection-type';

/**
 * 所有的字段均可选
 * @export
 * @interface UserSubjectCollectionModifyPayload
 */
export interface UserSubjectCollectionModifyPayload {
    /**
     * 修改条目收藏类型
     * @type {SubjectCollectionType}
     * @memberof UserSubjectCollectionModifyPayload
     */
    'type'?: SubjectCollectionType;
    /**
     * 评分，`0` 表示删除评分
     * @type {number}
     * @memberof UserSubjectCollectionModifyPayload
     */
    'rate'?: number;
    /**
     * 只能用于修改书籍条目进度
     * @type {number}
     * @memberof UserSubjectCollectionModifyPayload
     */
    'ep_status'?: number;
    /**
     * 只能用于修改书籍条目进度
     * @type {number}
     * @memberof UserSubjectCollectionModifyPayload
     */
    'vol_status'?: number;
    /**
     * 评价
     * @type {string}
     * @memberof UserSubjectCollectionModifyPayload
     */
    'comment'?: string;
    /**
     * 仅自己可见
     * @type {boolean}
     * @memberof UserSubjectCollectionModifyPayload
     */
    'private'?: boolean;
    /**
     * 不传或者 `null` 都会被忽略，传 `[]` 则会删除所有 tag。
     * @type {Array<string>}
     * @memberof UserSubjectCollectionModifyPayload
     */
    'tags'?: Array<string>;
}



