/* tslint:disable */
/* eslint-disable */
/**
 * Bangumi API
 * 你可以在 <https://api.bgm.tv/v0/oauth/> 生成一个 Access Token  ## 建议客户端开发者指定一个带有 APP 名称和版本的 User Agent，而非使用 HTTP 请求库默认的 UA  各种请求库的默认 UA 在未来可能会被禁用。 
 *
 * The version of the OpenAPI document: 2022-05-3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { UserAvatar } from './user-avatar';
import { UserGroup } from './user-group';

/**
 * 用户信息
 * @export
 * @interface User
 */
export interface User {
    /**
     * 用户 id
     * @type {number}
     * @memberof User
     */
    'id'?: number;
    /**
     * 用户主页地址
     * @type {string}
     * @memberof User
     */
    'url'?: string;
    /**
     * 用户名
     * @type {string}
     * @memberof User
     */
    'username'?: string;
    /**
     * 昵称
     * @type {string}
     * @memberof User
     */
    'nickname'?: string;
    /**
     * 
     * @type {UserAvatar}
     * @memberof User
     */
    'avatar'?: UserAvatar;
    /**
     * 签名
     * @type {string}
     * @memberof User
     */
    'sign'?: string;
    /**
     * 
     * @type {UserGroup}
     * @memberof User
     */
    'usergroup'?: UserGroup;
}

