/* tslint:disable */
/* eslint-disable */
/**
 * Bangumi API
 * 你可以在 <https://api.bgm.tv/v0/oauth/> 生成一个 Access Token  ## 建议客户端开发者指定一个带有 APP 名称和版本的 User Agent，而非使用 HTTP 请求库默认的 UA  各种请求库的默认 UA 在未来可能会被禁用。 
 *
 * The version of the OpenAPI document: 2022-05-3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Avatar } from './avatar';
import { UserGroup } from './user-group';

/**
 * 
 * @export
 * @interface User1
 */
export interface User1 {
    /**
     * 
     * @type {number}
     * @memberof User1
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof User1
     */
    'url': string;
    /**
     * 唯一用户名，初始与 UID 相同，可修改一次
     * @type {string}
     * @memberof User1
     */
    'username': string;
    /**
     * 
     * @type {string}
     * @memberof User1
     */
    'nickname': string;
    /**
     * 
     * @type {UserGroup}
     * @memberof User1
     */
    'user_group': UserGroup;
    /**
     * 
     * @type {Avatar}
     * @memberof User1
     */
    'avatar': Avatar;
    /**
     * 个人签名
     * @type {string}
     * @memberof User1
     */
    'sign': string;
}

