/* tslint:disable */
/* eslint-disable */
/**
 * Bangumi API
 * 你可以在 <https://next.bgm.tv/demo/access-token> 生成一个 Access Token  ## [关于 User Agent](https://github.com/bangumi/api/blob/master/docs-raw/user%20agent.md)  如果你在使用中遇到了问题，请优先使用 GitHub issue 提交问题。在 bangumi 小组发帖可能无法得到及时反馈。 
 *
 * The version of the OpenAPI document: 2025-02-5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SlimSubject } from './slim-subject';
// May contain unused imports in some cases
// @ts-ignore
import type { SubjectCollectionType } from './subject-collection-type';
// May contain unused imports in some cases
// @ts-ignore
import type { SubjectType } from './subject-type';

/**
 * 
 * @export
 * @interface UserSubjectCollection
 */
export interface UserSubjectCollection {
    /**
     * 
     * @type {number}
     * @memberof UserSubjectCollection
     */
    'subject_id': number;
    /**
     * 
     * @type {SubjectType}
     * @memberof UserSubjectCollection
     */
    'subject_type': SubjectType;
    /**
     * 
     * @type {number}
     * @memberof UserSubjectCollection
     */
    'rate': number;
    /**
     * 
     * @type {SubjectCollectionType}
     * @memberof UserSubjectCollection
     */
    'type': SubjectCollectionType;
    /**
     * 
     * @type {string}
     * @memberof UserSubjectCollection
     */
    'comment'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof UserSubjectCollection
     */
    'tags': Array<string>;
    /**
     * 
     * @type {number}
     * @memberof UserSubjectCollection
     */
    'ep_status': number;
    /**
     * 
     * @type {number}
     * @memberof UserSubjectCollection
     */
    'vol_status': number;
    /**
     * 本时间并不代表条目的收藏时间。修改评分，评价，章节观看状态等收藏信息时未更新此时间是一个 bug。请不要依赖此特性
     * @type {string}
     * @memberof UserSubjectCollection
     */
    'updated_at': string;
    /**
     * 
     * @type {boolean}
     * @memberof UserSubjectCollection
     */
    'private': boolean;
    /**
     * 
     * @type {SlimSubject}
     * @memberof UserSubjectCollection
     */
    'subject'?: SlimSubject;
}



