/* tslint:disable */
/* eslint-disable */
/**
 * Bangumi API
 * 你可以在 <https://api.bgm.tv/v0/oauth/> 生成一个 Access Token  ## 建议客户端开发者指定一个带有 APP 名称和版本的 User Agent，而非使用 HTTP 请求库默认的 UA  各种请求库的默认 UA 在未来可能会被禁用。 
 *
 * The version of the OpenAPI document: 2022-05-3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 用户组 - 1 = 管理员 - 2 = Bangumi 管理猿 - 3 = 天窗管理猿 - 4 = 禁言用户 - 5 = 禁止访问用户 - 8 = 人物管理猿 - 9 = 维基条目管理猿 - 10 = 用户 - 11 = 维基人
 * @export
 * @enum {string}
 */

export const UserGroup = {
    Admin: 1,
    BangumiAdmin: 2,
    DoujinAdmin: 3,
    MutedUser: 4,
    BlockedUser: 5,
    PersonAdmin: 8,
    WikiAdmin: 9,
    User: 10,
    WikiUser: 11
} as const;

export type UserGroup = typeof UserGroup[keyof typeof UserGroup];



