/**
 * Bangumi API
 * 你可以在 <https://api.bgm.tv/v0/oauth/> 生成一个 Access Token  ## 建议客户端开发者指定一个带有 APP 名称和版本的 User Agent，而非使用 HTTP 请求库默认的 UA  各种请求库的默认 UA 在未来可能会被禁用。 
 *
 * The version of the OpenAPI document: 2022-04-19
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 收藏状态 ID
 */
export type CollectionStatusId = 1 | 2 | 3 | 4 | 5;

export const CollectionStatusId = {
    NUMBER_1: 1 as CollectionStatusId,
    NUMBER_2: 2 as CollectionStatusId,
    NUMBER_3: 3 as CollectionStatusId,
    NUMBER_4: 4 as CollectionStatusId,
    NUMBER_5: 5 as CollectionStatusId
}
