/**
 * Bangumi API
 * 你可以在 <https://api.bgm.tv/v0/oauth/> 生成一个 Access Token  ## 建议客户端开发者指定一个带有 APP 名称和版本的 User Agent，而非使用 HTTP 请求库默认的 UA  各种请求库的默认 UA 在未来可能会被禁用。 
 *
 * The version of the OpenAPI document: 2022-04-19
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 用户组 <br> 1 = 管理员 <br> 2 = Bangumi 管理猿 <br> 3 = 天窗管理猿 <br> 4 = 禁言用户 <br> 5 = 禁止访问用户 <br> 8 = 人物管理猿 <br> 9 = 维基条目管理猿 <br> 10 = 用户 <br> 11 = 维基人
 */
export type UserGroup = 1 | 2 | 3 | 4 | 5 | 8 | 9 | 10 | 11;

export const UserGroup = {
    NUMBER_1: 1 as UserGroup,
    NUMBER_2: 2 as UserGroup,
    NUMBER_3: 3 as UserGroup,
    NUMBER_4: 4 as UserGroup,
    NUMBER_5: 5 as UserGroup,
    NUMBER_8: 8 as UserGroup,
    NUMBER_9: 9 as UserGroup,
    NUMBER_10: 10 as UserGroup,
    NUMBER_11: 11 as UserGroup
}
