/**
 * Bangumi API
 * 你可以在 <https://api.bgm.tv/v0/oauth/> 生成一个 Access Token  ## 建议客户端开发者指定一个带有 APP 名称和版本的 User Agent，而非使用 HTTP 请求库默认的 UA  各种请求库的默认 UA 在未来可能会被禁用。 
 *
 * The version of the OpenAPI document: 2022-05-3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Headers } from '../Headers';
import { Observable } from 'rxjs';
import { CharacterDetail } from '../model/characterDetail';
import { CharacterPerson } from '../model/characterPerson';
import { CharacterRevision } from '../model/characterRevision';
import { CollectionStatusType } from '../model/collectionStatusType';
import { CollectionType } from '../model/collectionType';
import { DetailedRevision } from '../model/detailedRevision';
import { EpStatusType } from '../model/epStatusType';
import { EpType } from '../model/epType';
import { EpisodeDetail } from '../model/episodeDetail';
import { ErrorDetail } from '../model/errorDetail';
import { Index } from '../model/index';
import { InlineResponse200 } from '../model/inlineResponse200';
import { InlineResponse2001 } from '../model/inlineResponse2001';
import { InlineResponse2002 } from '../model/inlineResponse2002';
import { InlineResponse2003 } from '../model/inlineResponse2003';
import { InlineResponse2004 } from '../model/inlineResponse2004';
import { InlineResponse2005 } from '../model/inlineResponse2005';
import { PagedEpisode } from '../model/pagedEpisode';
import { PagedIndexSubject } from '../model/pagedIndexSubject';
import { PagedRevision } from '../model/pagedRevision';
import { PagedUserCollection } from '../model/pagedUserCollection';
import { PersonCharacter } from '../model/personCharacter';
import { PersonDetail } from '../model/personDetail';
import { PersonRevision } from '../model/personRevision';
import { PolApiV0ModelsRelatedSubject } from '../model/polApiV0ModelsRelatedSubject';
import { PolApiV0ModelsSubjectRelatedSubject } from '../model/polApiV0ModelsSubjectRelatedSubject';
import { RelatedCharacter } from '../model/relatedCharacter';
import { RelatedPerson } from '../model/relatedPerson';
import { ResponseGroup } from '../model/responseGroup';
import { StatusCode } from '../model/statusCode';
import { Subject } from '../model/subject';
import { SubjectRevision } from '../model/subjectRevision';
import { SubjectType } from '../model/subjectType';
import { SubjectTypeName } from '../model/subjectTypeName';
import { User1 } from '../model/user1';
import HttpResponse from '../HttpResponse';


export interface DefaultServiceInterface {
    /**
    * 批量更新收视进度
    * 
    * @param subject_id 条目 ID
    * @param watched_eps 如看到 123 话则 POST &#x60;123&#x60; &lt;br&gt; 书籍条目传 watched_eps 与 watched_vols 至少其一
    * @param watched_vols 如看到第 3 卷则 POST &#x60;3&#x60;, 仅对书籍条目有效
    */

    batchUpdateEpisodeStatusBySubjectId(subject_id: number, watched_eps: string, watched_vols?: string, observe?: 'body', headers?: Headers): Observable<StatusCode>;
    batchUpdateEpisodeStatusBySubjectId(subject_id: number, watched_eps: string, watched_vols?: string, observe?: 'response', headers?: Headers): Observable<HttpResponse<StatusCode>>;
    /**
    * 每日放送
    * 
    */

    getCalendar(observe?: 'body', headers?: Headers): Observable<Array<InlineResponse2003>>;
    getCalendar(observe?: 'response', headers?: Headers): Observable<HttpResponse<Array<InlineResponse2003>>>;
    /**
    * Get Character Detail
    * cache with 60s
    * @param character_id 
    */

    getCharacterById(character_id: number, observe?: 'body', headers?: Headers): Observable<CharacterDetail>;
    getCharacterById(character_id: number, observe?: 'response', headers?: Headers): Observable<HttpResponse<CharacterDetail>>;
    /**
    * Get Character Revision
    * 
    * @param revision_id 
    */

    getCharacterRevisionByRevisionId(revision_id: number, observe?: 'body', headers?: Headers): Observable<CharacterRevision>;
    getCharacterRevisionByRevisionId(revision_id: number, observe?: 'response', headers?: Headers): Observable<HttpResponse<CharacterRevision>>;
    /**
    * Get Character Revisions
    * 
    * @param character_id 
    * @param limit 
    * @param offset 
    */

    getCharacterRevisions(character_id: number, limit?: number, offset?: number, observe?: 'body', headers?: Headers): Observable<PagedRevision>;
    getCharacterRevisions(character_id: number, limit?: number, offset?: number, observe?: 'response', headers?: Headers): Observable<HttpResponse<PagedRevision>>;
    /**
    * 获取指定条目收藏信息
    * 
    * @param subject_id 条目 ID
    */

    getCollectionBySubjectId(subject_id: number, observe?: 'body', headers?: Headers): Observable<InlineResponse2005>;
    getCollectionBySubjectId(subject_id: number, observe?: 'response', headers?: Headers): Observable<HttpResponse<InlineResponse2005>>;
    /**
    * Get Episode
    * 
    * @param episode_id 
    */

    getEpisodeById(episode_id: number, observe?: 'body', headers?: Headers): Observable<EpisodeDetail>;
    getEpisodeById(episode_id: number, observe?: 'response', headers?: Headers): Observable<HttpResponse<EpisodeDetail>>;
    /**
    * Get Episode Revision
    * 
    * @param revision_id 
    */

    getEpisodeRevisionByRevisionId(revision_id: number, observe?: 'body', headers?: Headers): Observable<DetailedRevision>;
    getEpisodeRevisionByRevisionId(revision_id: number, observe?: 'response', headers?: Headers): Observable<HttpResponse<DetailedRevision>>;
    /**
    * Get Episode Revisions
    * 
    * @param episode_id 
    * @param limit 
    * @param offset 
    */

    getEpisodeRevisions(episode_id: number, limit?: number, offset?: number, observe?: 'body', headers?: Headers): Observable<PagedRevision>;
    getEpisodeRevisions(episode_id: number, limit?: number, offset?: number, observe?: 'response', headers?: Headers): Observable<HttpResponse<PagedRevision>>;
    /**
    * 更新收视进度
    * 
    * @param id 章节 ID
    * @param status 收视类型，参考 [EpStatusType](#model-EpStatusType)
    */

    getEpisodeStatus(id: number, status: EpStatusType, observe?: 'body', headers?: Headers): Observable<StatusCode>;
    getEpisodeStatus(id: number, status: EpStatusType, observe?: 'response', headers?: Headers): Observable<HttpResponse<StatusCode>>;
    /**
    * Get Episodes
    * 
    * @param subject_id 
    * @param type 参照章节的&#x60;type&#x60;
    * @param limit 
    * @param offset 
    */

    getEpisodes(subject_id: number, type?: EpType, limit?: number, offset?: number, observe?: 'body', headers?: Headers): Observable<PagedEpisode>;
    getEpisodes(subject_id: number, type?: EpType, limit?: number, offset?: number, observe?: 'response', headers?: Headers): Observable<HttpResponse<PagedEpisode>>;
    /**
    * Get Index By Id
    * 
    * @param index_id 
    */

    getIndexById(index_id: number, observe?: 'body', headers?: Headers): Observable<Index>;
    getIndexById(index_id: number, observe?: 'response', headers?: Headers): Observable<HttpResponse<Index>>;
    /**
    * Get Index Subjects
    * 
    * @param index_id 
    * @param type 
    * @param limit 
    * @param offset 
    */

    getIndexSubjectsByIndexId(index_id: number, type?: SubjectType, limit?: number, offset?: number, observe?: 'body', headers?: Headers): Observable<PagedIndexSubject>;
    getIndexSubjectsByIndexId(index_id: number, type?: SubjectType, limit?: number, offset?: number, observe?: 'response', headers?: Headers): Observable<HttpResponse<PagedIndexSubject>>;
    /**
    * Get User
    * 返回当前 Access Token 对应的用户信息
    */

    getMyself(observe?: 'body', headers?: Headers): Observable<User1>;
    getMyself(observe?: 'response', headers?: Headers): Observable<HttpResponse<User1>>;
    /**
    * Get Person
    * cache with 60s
    * @param person_id 
    */

    getPersonById(person_id: number, observe?: 'body', headers?: Headers): Observable<PersonDetail>;
    getPersonById(person_id: number, observe?: 'response', headers?: Headers): Observable<HttpResponse<PersonDetail>>;
    /**
    * Get Person Revision
    * 
    * @param revision_id 
    */

    getPersonRevisionByRevisionId(revision_id: number, observe?: 'body', headers?: Headers): Observable<PersonRevision>;
    getPersonRevisionByRevisionId(revision_id: number, observe?: 'response', headers?: Headers): Observable<HttpResponse<PersonRevision>>;
    /**
    * Get Person Revisions
    * 
    * @param person_id 
    * @param limit 
    * @param offset 
    */

    getPersonRevisions(person_id: number, limit?: number, offset?: number, observe?: 'body', headers?: Headers): Observable<PagedRevision>;
    getPersonRevisions(person_id: number, limit?: number, offset?: number, observe?: 'response', headers?: Headers): Observable<HttpResponse<PagedRevision>>;
    /**
    * get person related characters
    * 
    * @param person_id 
    */

    getRelatedCharactersByPersonId(person_id: number, observe?: 'body', headers?: Headers): Observable<Array<PersonCharacter>>;
    getRelatedCharactersByPersonId(person_id: number, observe?: 'response', headers?: Headers): Observable<HttpResponse<Array<PersonCharacter>>>;
    /**
    * Get Subject Characters
    * 
    * @param subject_id 
    */

    getRelatedCharactersBySubjectId(subject_id: number, observe?: 'body', headers?: Headers): Observable<Array<RelatedCharacter>>;
    getRelatedCharactersBySubjectId(subject_id: number, observe?: 'response', headers?: Headers): Observable<HttpResponse<Array<RelatedCharacter>>>;
    /**
    * get character related persons
    * 
    * @param character_id 
    */

    getRelatedPersonsByCharacterId(character_id: number, observe?: 'body', headers?: Headers): Observable<Array<CharacterPerson>>;
    getRelatedPersonsByCharacterId(character_id: number, observe?: 'response', headers?: Headers): Observable<HttpResponse<Array<CharacterPerson>>>;
    /**
    * Get Subject Persons
    * 
    * @param subject_id 
    */

    getRelatedPersonsBySubjectId(subject_id: number, observe?: 'body', headers?: Headers): Observable<Array<RelatedPerson>>;
    getRelatedPersonsBySubjectId(subject_id: number, observe?: 'response', headers?: Headers): Observable<HttpResponse<Array<RelatedPerson>>>;
    /**
    * get character related subjects
    * 
    * @param character_id 
    */

    getRelatedSubjectsByCharacterId(character_id: number, observe?: 'body', headers?: Headers): Observable<Array<PolApiV0ModelsRelatedSubject>>;
    getRelatedSubjectsByCharacterId(character_id: number, observe?: 'response', headers?: Headers): Observable<HttpResponse<Array<PolApiV0ModelsRelatedSubject>>>;
    /**
    * get person related subjects
    * 
    * @param person_id 
    */

    getRelatedSubjectsByPersonId(person_id: number, observe?: 'body', headers?: Headers): Observable<Array<PolApiV0ModelsRelatedSubject>>;
    getRelatedSubjectsByPersonId(person_id: number, observe?: 'response', headers?: Headers): Observable<HttpResponse<Array<PolApiV0ModelsRelatedSubject>>>;
    /**
    * Get Subject Relations
    * 
    * @param subject_id 
    */

    getRelatedSubjectsBySubjectId(subject_id: number, observe?: 'body', headers?: Headers): Observable<Array<PolApiV0ModelsSubjectRelatedSubject>>;
    getRelatedSubjectsBySubjectId(subject_id: number, observe?: 'response', headers?: Headers): Observable<HttpResponse<Array<PolApiV0ModelsSubjectRelatedSubject>>>;
    /**
    * 获取条目
    * cache with 300s
    * @param subject_id 
    */

    getSubjectById(subject_id: number, observe?: 'body', headers?: Headers): Observable<Subject>;
    getSubjectById(subject_id: number, observe?: 'response', headers?: Headers): Observable<HttpResponse<Subject>>;
    /**
    * Get Subject Revision
    * 
    * @param revision_id 
    */

    getSubjectRevisionByRevisionId(revision_id: number, observe?: 'body', headers?: Headers): Observable<SubjectRevision>;
    getSubjectRevisionByRevisionId(revision_id: number, observe?: 'response', headers?: Headers): Observable<HttpResponse<SubjectRevision>>;
    /**
    * Get Subject Revisions
    * 
    * @param subject_id 
    * @param limit 
    * @param offset 
    */

    getSubjectRevisions(subject_id: number, limit?: number, offset?: number, observe?: 'body', headers?: Headers): Observable<PagedRevision>;
    getSubjectRevisions(subject_id: number, limit?: number, offset?: number, observe?: 'response', headers?: Headers): Observable<HttpResponse<PagedRevision>>;
    /**
    * Get User by name
    * 获取用户信息，设置了 username 之后无法使用 UID 查询。
    * @param username 
    */

    getUserByName(username: string, observe?: 'body', headers?: Headers): Observable<User1>;
    getUserByName(username: string, observe?: 'response', headers?: Headers): Observable<HttpResponse<User1>>;
    /**
    * 用户收藏统计
    * 
    * @param username 用户名 &lt;br&gt; 也可使用 UID
    * @param app_id [https://bgm.tv/dev/app](https://bgm.tv/dev/app) 申请到的 App ID
    */

    getUserCollectionStatusByUsername(username: string, app_id: string, observe?: 'body', headers?: Headers): Observable<Array<InlineResponse2001>>;
    getUserCollectionStatusByUsername(username: string, app_id: string, observe?: 'response', headers?: Headers): Observable<HttpResponse<Array<InlineResponse2001>>>;
    /**
    * 用户收藏概览
    * 
    * @param username 用户名 &lt;br&gt; 也可使用 UID
    * @param subject_type 条目类型，详见 [SubjectTypeName](#model-SubjectTypeName)
    * @param app_id [https://bgm.tv/dev/app](https://bgm.tv/dev/app) 申请到的 App ID
    * @param max_results 显示条数 &lt;br&gt; 最多 25
    */

    getUserCollectionsBySubjectType(username: string, subject_type: SubjectTypeName, app_id: string, max_results?: number, observe?: 'body', headers?: Headers): Observable<Array<InlineResponse200>>;
    getUserCollectionsBySubjectType(username: string, subject_type: SubjectTypeName, app_id: string, max_results?: number, observe?: 'response', headers?: Headers): Observable<HttpResponse<Array<InlineResponse200>>>;
    /**
    * 获取用户收藏
    * 获取对应用户的收藏，查看私有收藏需要access token。
    * @param username 设置了 username 后无法使用UID
    * @param subject_type 条目类型，默认为全部  具体含义见 [SubjectType](#model-SubjectType)
    * @param type 收藏类型，默认为全部  具体含义见 [CollectionType](#model-CollectionType)
    * @param limit 
    * @param offset 
    */

    getUserCollectionsByUsername(username: string, subject_type?: SubjectType, type?: CollectionType, limit?: number, offset?: number, observe?: 'body', headers?: Headers): Observable<PagedUserCollection>;
    getUserCollectionsByUsername(username: string, subject_type?: SubjectType, type?: CollectionType, limit?: number, offset?: number, observe?: 'response', headers?: Headers): Observable<HttpResponse<PagedUserCollection>>;
    /**
    * 用户收视进度
    * 
    * @param username 用户名 &lt;br&gt; 也可使用 UID
    * @param subject_id 条目 ID &lt;br&gt; 获取指定条目收视进度
    */

    getUserProgressByUsername(username: string, subject_id?: number, observe?: 'body', headers?: Headers): Observable<Array<InlineResponse2002>>;
    getUserProgressByUsername(username: string, subject_id?: number, observe?: 'response', headers?: Headers): Observable<HttpResponse<Array<InlineResponse2002>>>;
    /**
    * 条目搜索
    * 
    * @param keywords 关键词 &lt;br&gt; 需要 URL Encode
    * @param type 条目类型，参考 [SubjectType](#model-SubjectType)
    * @param responseGroup 返回数据大小，参考 [ResponseGroup](#model-ResponseGroup) &lt;br&gt; 默认为 small
    * @param start 开始条数
    * @param max_results 每页条数 &lt;br&gt; 最多 25
    */

    searchSubjectByKeywords(keywords: string, type?: SubjectType, responseGroup?: ResponseGroup, start?: number, max_results?: number, observe?: 'body', headers?: Headers): Observable<InlineResponse2004>;
    searchSubjectByKeywords(keywords: string, type?: SubjectType, responseGroup?: ResponseGroup, start?: number, max_results?: number, observe?: 'response', headers?: Headers): Observable<HttpResponse<InlineResponse2004>>;
    /**
    * 管理收藏
    * 管理收藏。Content-type必须为multipart/form-data或application/x-www-form-urlencoded，参数都得放在body里。
    * @param subject_id 条目 ID
    * @param action 收藏动作 &lt;br&gt; create &#x3D; 添加收藏 &lt;br&gt; update &#x3D; 更新收藏 &lt;br&gt; 可以统一使用 &#x60;update&#x60;，系统会自动判断需要新建还是更新收藏
    * @param status 
    * @param comment 简评
    * @param tags 标签 &lt;br&gt; 以半角空格分割
    * @param rating 评分 &lt;br&gt; 1-10 &lt;br&gt; 不填默认重置为未评分
    * @param privacy 收藏隐私 &lt;br&gt; 0 &#x3D; 公开 &lt;br&gt; 1 &#x3D; 私密 &lt;br&gt; 不填默认为0
    */

    updateCollectionBySubjectIdWithAction(subject_id: number, action: 'create' | 'update', status: CollectionStatusType, comment?: string, tags?: string, rating?: number, privacy?: number, observe?: 'body', headers?: Headers): Observable<InlineResponse2005>;
    updateCollectionBySubjectIdWithAction(subject_id: number, action: 'create' | 'update', status: CollectionStatusType, comment?: string, tags?: string, rating?: number, privacy?: number, observe?: 'response', headers?: Headers): Observable<HttpResponse<InlineResponse2005>>;
    /**
    * 更新收视进度
    * 
    * @param id 章节 ID
    * @param status 收视类型，参考 [EpStatusType](#model-EpStatusType)
    * @param ep_id 使用 POST 批量更新 &lt;br&gt; 将章节以半角逗号分隔，如 &#x60;3697,3698,3699&#x60;。请求时 URL 中的 ep_id 为最后一个章节 ID
    */

    updateEpisodeStatus(id: number, status: EpStatusType, ep_id?: string, observe?: 'body', headers?: Headers): Observable<StatusCode>;
    updateEpisodeStatus(id: number, status: EpStatusType, ep_id?: string, observe?: 'response', headers?: Headers): Observable<HttpResponse<StatusCode>>;
}
